services:
  postgres:
    container_name: localPostgresSQLDB
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=PoshStoreDatabase'
      - 'POSTGRES_PASSWORD=5422Ansov#!'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5432:5432'
